= Jun Xiang - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== CS2113T Project: DiveLog
== Overview

*DiveLog* is a desktop application that mainly uses CLI as a user interface. Dive Log provides a simple way for underwater divers to input details of their dives such as the time they spent at a particular depth, and the application will keep track of their nitrogen levels.
This allows divers to plan their next trip safely.

Dive Log is able to calculate accurately the diver’s current Blood Nitrogen Composition, which is used to evaluate when it will be safe to dive again, and for how long.


== Summary of contributions
* *Code Contributed* [https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=cjunxiang&sort=displayName&since=2018-09-12&until=2018-11-02&timeframe=day&reverse=false&repoSort=true[Cjunx]]

* *Major enhancement*: Implemented a *Planning Mode*
** What it does: This feature allows users to be able to plan for future dives without the fear of corrupting their current data.
When the users exit planning mode, the data is restored to before when entered planning mode.
If the user wants to transfer planning data to normal mode, the user can use `portover` command.
** Justification: This is a major feature of the app as divers often want to plan their dives ahead of their trips. This
also helps to reduce the instance where divers cannot board a plane ride due to
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.

* *Minor enhancement*: Created Time, OurDate parameters in a `DiveSession` and a helper class `CompareUtils`. The two parameters
are crucial in logging a dive, and also in calculations of Pressure Groups which is the main feature of our app. `CompareUtils`
contain methods that help

* *Other contributions*:


** Enhancements to existing features:
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])

** Documentation:
*** [UG] Introduced tables to organise information (Cosmetics)
    https://github.com[#14]
*** [UG] Tweaked the whole User Guide's tone to sound more interactive
    https://github.com[#14]
*** [UG] Documented new commands
    https://github.com[#14]
*** [DG] Added components pertaining to Sorting, Planning Mode & New parameters in a Dive:
    https://github.com[#14]
    https://github.com[#14]
    https://github.com[#14]


https://github.com/CS2113-AY1819S1-W13-2/main/commit/0829afba21bceb1580ee72431b9c4fd3bc068644[#41 Fine tuned Compare Util and TimeZone] +
https://github.com/CS2113-AY1819S1-W13-2/main/commit/4e1156e7682e38e35f11cbefb4b4924e55ea165f[#66 Sorting is up] +
https://github.com/CS2113-AY1819S1-W13-2/main/commit/cd9c7b404eda71e47ca6714b65ae678e9a963110[#66 Planning mode] +
https://github.com/CS2113-AY1819S1-W13-2/main/commit/9f8e2a3e41224a95130cb3692ed1c914f9239fb7[#66 UG Rephrasing] +
https://github.com/CS2113-AY1819S1-W13-2/main/commit/5bf250378b702049f8f93e030d38561f2c3a0f4e[#128 PortOver Command] +
https://github.com/CS2113-AY1819S1-W13-2/main/commit/5bf250378b702049f8f93e030d38561f2c3a0f4e[#128 Refine Exit Planning Mode] +
https://github.com/CS2113-AY1819S1-W13-2/main/pull/135[#135 Updates to User Guide]


** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=sortby]
include::../UserGuide.adoc[tag=newplan]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=newparam]
include::../DeveloperGuide.adoc[tag=sorting]
include::../DeveloperGuide.adoc[tag=planning]