package seedu.divelog.model.util;

import seedu.divelog.commons.util.CompareUtil;
import seedu.divelog.logic.pressuregroup.exceptions.LimitExceededException;
import seedu.divelog.model.DiveLog;
import seedu.divelog.model.ReadOnlyDiveLog;
import seedu.divelog.model.dive.DepthProfile;
import seedu.divelog.model.dive.DiveSession;
import seedu.divelog.model.dive.Location;
import seedu.divelog.model.dive.OurDate;
import seedu.divelog.model.dive.PressureGroup;
import seedu.divelog.model.dive.Time;
import seedu.divelog.model.dive.TimeZone;
import seedu.divelog.model.dive.exceptions.DiveOverlapsException;
import seedu.divelog.model.dive.exceptions.InvalidTimeException;


/**
 * Contains utility methods for populating {@code DiveLog} with sample data.
 */
public class SampleDataUtil {
    public static DiveSession[] getSampleDives() {
        long today = CompareUtil.getCurrentDateTimeLong();
        String todayString = CompareUtil.readDateFromLong(today);
        return new DiveSession[] {
            new DiveSession(new OurDate(todayString),
                        new Time("0700"),
                        new Time("0745"),
                        new OurDate(todayString),
                        new Time("0800"),
                        new PressureGroup("A"),
                        new PressureGroup("T"),
                        new Location("Sentosa, Singapore"),
                        new DepthProfile(15.0f),
                        new TimeZone("+8")), new DiveSession(new OurDate("04112018"),
                        new Time("1700"),
                        new Time("1745"),
                        new OurDate("04112018"),
                        new Time("1750"),
                        new PressureGroup("A"),
                        new PressureGroup("I"),
                        new Location("Sentosa, Singapore"),
                        new DepthProfile(5.0f),
                        new TimeZone("+8")), new DiveSession(new OurDate("02112018"),
                new Time("0700"),
                new Time("0710"),
                new OurDate("02112018"),
                new Time("0715"),
                new PressureGroup("A"),
                new PressureGroup("J"),
                new Location("Sugar Wreck, Perhentian Islands, Malaysia"),
                new DepthProfile(30.0f),
                new TimeZone("+8")), new DiveSession(new OurDate("02112018"),
                new Time("0900"),
                new Time("0906"),
                new OurDate("02112018"),
                new Time("0910"),
                new PressureGroup("B"),
                new PressureGroup("K"),
                new Location("Sugar Wreck, Perhentian Islands, Malaysia"),
                new DepthProfile(30.0f),
                new TimeZone("+8")), new DiveSession(new OurDate("01112018"),
                new Time("0944"),
                new Time("1140"),
                new OurDate("01112018"),
                new Time("1145"),
                new PressureGroup("A"),
                new PressureGroup("T"),
                new Location("Atago Maru Wreck, Miri, Malaysia"),
                new DepthProfile(10.0f),
                new TimeZone("+8")), new DiveSession(new OurDate("31102018"),
                new Time("1230"),
                new Time("1255"),
                new OurDate("31102018"),
                new Time("1300"),
                new PressureGroup("A"),
                new PressureGroup("M"),
                new Location("WW II Wrecks, Kuching, Malaysia"),
                new DepthProfile(20.0f),
                new TimeZone("+8")), new DiveSession(new OurDate("30102018"),
                new Time("1630"),
                new Time("1640"),
                new OurDate("30102018"),
                new Time("1645"),
                new PressureGroup("A"),
                new PressureGroup("J"),
                new Location("Pulau Lima, Redang, Malaysia"),
                new DepthProfile(30.0f),
                new TimeZone("+8")), new DiveSession(new OurDate("30102018"),
                new Time("1800"),
                new Time("1807"),
                new OurDate("30102018"),
                new Time("1812"),
                new PressureGroup("B"),
                new PressureGroup("M"),
                new Location("Pulau Lima, Redang, Malaysia"),
                new DepthProfile(30.0f),
                new TimeZone("+8")), new DiveSession(new OurDate("05082018"),
                new Time("1100"),
                new Time("1145"),
                new OurDate("05082018"),
                new Time("1200"),
                new PressureGroup("A"),
                new PressureGroup("M"),
                new Location("Bali, Indonesia"),
                new DepthProfile(14.0f),
                new TimeZone("+8")), new DiveSession(new OurDate("05082018"),
                    new Time("1500"),
                    new Time("1545"),
                    new OurDate("05082018"),
                    new Time("1600"),
                    new PressureGroup("A"),
                    new PressureGroup("M"),
                    new Location("Bali, Indonesia"),
                    new DepthProfile(10.0f),
                    new TimeZone("+8")), new DiveSession(new OurDate("08082018"),
                    new Time("1100"),
                    new Time("1145"),
                    new OurDate("08082018"),
                    new Time("1200"),
                    new PressureGroup("A"),
                    new PressureGroup("L"),
                    new Location("Tioman, Malaysia"),
                    new DepthProfile(8.0f),
                    new TimeZone("+8")), new DiveSession(new OurDate("08052018"),
                new Time("1000"),
                new Time("1125"),
                new OurDate("08052018"),
                new Time("1130"),
                new PressureGroup("A"),
                new PressureGroup("Q"),
                new Location("Great Barrier Reef, Queensland, Australia"),
                new DepthProfile(6.0f),
                new TimeZone("+10")), new DiveSession(new OurDate("07052018"),
                new Time("0900"),
                new Time("0925"),
                new OurDate("07052018"),
                new Time("0930"),
                new PressureGroup("A"),
                new PressureGroup("K"),
                new Location("HMAS Brisbane, Queensland, Australia"),
                new DepthProfile(17.0f),
                new TimeZone("+10")), new DiveSession(new OurDate("07052018"),
                new Time("1030"),
                new Time("1055"),
                new OurDate("07052018"),
                new Time("1102"),
                new PressureGroup("C"),
                new PressureGroup("Q"),
                new Location("HMAS Brisbane, Queensland, Australia"),
                new DepthProfile(15.0f),
                new TimeZone("+10")), new DiveSession(new OurDate("06052018"),
                new Time("1010"),
                new Time("1025"),
                new OurDate("06052018"),
                new Time("1031"),
                new PressureGroup("A"),
                new PressureGroup("K"),
                new Location("SS Yongala, Queensland, Australia"),
                new DepthProfile(25.0f),
                new TimeZone("+10")), new DiveSession(new OurDate("06052018"),
                new Time("1705"),
                new Time("1730"),
                new OurDate("06052018"),
                new Time("1735"),
                new PressureGroup("A"),
                new PressureGroup("M"),
                new Location("SS Yongala, Queensland, Australia"),
                new DepthProfile(20.0f),
                new TimeZone("+10")), new DiveSession(new OurDate("05052018"),
                new Time("0807"),
                new Time("0820"),
                new OurDate("05052018"),
                new Time("0823"),
                new PressureGroup("A"),
                new PressureGroup("B"),
                new Location("The Whitsundays, Queensland, Australia"),
                new DepthProfile(6.0f),
                new TimeZone("+10")), new DiveSession(new OurDate("05052018"),
                new Time("0853"),
                new Time("0915"),
                new OurDate("05052018"),
                new Time("0920"),
                new PressureGroup("B"),
                new PressureGroup("I"),
                new Location("The Whitsundays, Queensland, Australia"),
                new DepthProfile(8.0f),
                new TimeZone("+10")), new DiveSession(new OurDate("05052018"),
                new Time("1002"),
                new Time("1028"),
                new OurDate("05052018"),
                new Time("1032"),
                new PressureGroup("D"),
                new PressureGroup("L"),
                new Location("The Whitsundays, Queensland, Australia"),
                new DepthProfile(8.0f),
                new TimeZone("+10")), new DiveSession(new OurDate("05052018"),
                new Time("1415"),
                new Time("1456"),
                new OurDate("05052018"),
                new Time("1500"),
                new PressureGroup("A"),
                new PressureGroup("K"),
                new Location("The Whitsundays, Queensland, Australia"),
                new DepthProfile(5.0f),
                new TimeZone("+10"))
        };
    }

    public static ReadOnlyDiveLog getSampleDiveLog() {
        DiveLog sampleDl = new DiveLog();
        for (DiveSession dive : getSampleDives()) {
            try {
                sampleDl.addDive(dive);
            } catch (LimitExceededException | InvalidTimeException | DiveOverlapsException e) {
                throw new AssertionError("Sample data should follow convention of dialogs");
            }
        }
        return sampleDl;
    }

}
